### ISSUE TITLE
Clarification of `estimateSize` option

### ISSUE THREAD

**Issue by dylanesque** [tannerlinsley/react-virtual#121]
The API documentation, when combined with the examples, raises questions about the `estimateSize` option of the 'useVirtual' hook. The docs say that it's required, but I'm seeing a number of instances (at least in the dynamic examples) where it isn't specified. It looks as if there's a default value of 50 in the source code? I can create a PR with the docs change to highlight this, but I wanted to be sure that I do understand the way it actually works.

**Comment by piecyk** [comment]
@dylanesque good catch, i think we should mention in docs the default `() => 50` 

So here we have two cases, with fixed size or unknown

1. In case of **fixed size** if your item is not 50, estimateSize need to be provided. Because base on this value the visible range is calculate overall height of list etc. That's why docs says it's `required`.

2. In case of **unknown**. On initial render we didn't read the size of item yet so the default **50** will be used. As with every `magic` number this can be way off. For example if you know that your item are in range of 100 to 200, changing it to 150 makes more sense. Would recommend always test and set default estimateSize for particular use case.

**Comment by dylanesque** [comment]
Thanks for the clarification @piecyk, I'll get a PR in with that context in mind!

**Comment by piecyk** [comment]
@dylanesque do you think this is now resolved? If so, could you close the issue? Thanks.

**Comment by dylanesque** [comment]
Closing, this change has been enacted in the docs.
