### ISSUE TITLE
useVirtual sometimes misses changes to parentRef

### ISSUE THREAD

**Issue by dantman** [tannerlinsley/react-virtual#146]
The way useVirtual and useRect handles getting the parent node is unreliable and sometimes never actually starts observing the node.

useVirtual requires that parentRef is a RefObject and not a dom node. useRect then uses a layout effect to turn that into state.

As a result useRect will only ever observe an element if the component calling it does a render that triggers a layout effect at the right time.

I was using useVirtual in a setup where the "parent" was a child inside a popup. As a result useRect never actually recieves the ref if I use a normal useRef.

There would be an easy fix of course. If parentRef didn't have to be a Ref object and could instead be the element directly I could trivially use `const [parentRef, setParentRef] = useState(null);` and swap `ref: parentRef` for `ref: setParentRef` and useRect would reliably get the node.

**Comment by tannerlinsley** [comment]
We have a pretty strict policy on requiring a codesandbox that can reproduce a bug and help us dig in deeper. If you would be so kind to open a new issue with one, it would help immensely. If you can't get it to reproduce in a sandbox but still need help, open a new discussion instead of an issue and we can talk there until a repro can be found.
