### ISSUE TITLE
Infinite scroll example fail with fast scrolling

### ISSUE THREAD

**Issue by joccd** [tannerlinsley/react-virtual#161]
Hi !

Thanks for your amazing work.
In your example : https://codesandbox.io/s/github/tannerlinsley/react-virtual/tree/master/examples/infinite-scroll

If I scroll slowly to bottom -> It works
If I scroll quickly to bottom -> "Loading more..." remains
![image](https://user-images.githubusercontent.com/22839734/124578537-972c2480-de4e-11eb-9cf3-13d3cc93557e.png)

Indeed, lastItem.index and flatPosts.length equal 10

Fail on both Chrome and Firefox, I have a good laptop, rather powerful.

Regards,
Joccd

**Comment by idfunctor** [comment]
@joccd  It's due to a small bug in the example; it's not related to a problem with the library itself.

Here's the updated example. https://codesandbox.io/s/jolly-bartik-t7sxj?file=/src/index.js
Had to change `===` to `>=` (in my example it's line 81)

 @tannerlinsley please feel free to update official example as well.

**Comment by gregsifr** [comment]
@idfunctor Thank you for sharing the solution to the equality bug! Any idea how to make the heights dynamic? I followed the examples but it either errors out or overlaps depending on it I set the value of `height` to `${flatPosts[virtualRow.index]}px` or `${virtualRow.size}px`.

This link should be a minimal example (line 99 and 100 are there those height values are) https://codesandbox.io/s/black-rain-7t80x?file=/src/index.js
