### ISSUE TITLE
react-virtual testing

### ISSUE THREAD

**Issue by gargroh** [tannerlinsley/react-virtual#29]
I migrated to react-virtual for a component using react-table and believe me after migration when i look at the code it now has much better DX.

One thing i want to check, has anyone tried to add tests to react-virtual, because it only renders the over-scanned rows in test.

@tannerlinsley i checked https://github.com/tannerlinsley/react-virtual/blob/master/src/tests/index.test.js, here also only overscanned rows are being tested it is not be able to render/test as expected.

Let me know if anyone has solution or am i missing something ?

**Comment by sibelius** [comment]
@gargroh do you have an example of react-table with react-virtual?

**Comment by farhadniaz** [comment]
I also want to make tests but I have some problems with react-virtual virtualRow.measureRef(el).
It's working well without testing. but when I wrote a test for it, react throw error for maximum updates on reactjs DOM. 
`ref= {(el) => {
        virtualRow.measureRef(el);
        virtualColumn.measureRef(el);
      }}`
In normal usage without testing its working well but with testing!!

**Comment by JReinhold** [comment]
I'm seeing the same issue as @farhadniaz, maybe it's related to #5

**Comment by adbayb** [comment]
Thanks @JReinhold , I have come to the same conclusion before seing the issue. 

@tannerlinsley It'll be great if the library fixes this issue internally to avoid external mocking relying on implementation details.

For this, I can think of two possible solutions:
- **Not recommended** Relying on `process.env.NODE_ENV` check => Not recommended since it depends greatly on the testing runtime (jest set it by default but not mocha for example) and environment (it could overwritten in the consumer land)
- **Preferred** Having an update threshold: we avoid triggering new updates (via `setMeasuredCache`) after X updates  with the same returned JSDom like object shape for `el.getBoundingClientRect()` (eg. `{ bottom: 0, height: 0, left: 0, right: 0, width: 0 }`)

**Comment by adbayb** [comment]
Thanks @JReinhold , I have come to the same conclusion. 

@tannerlinsley I've sent a pull request to fix it https://github.com/tannerlinsley/react-virtual/pull/45
