### ISSUE TITLE
react-window

### ISSUE THREAD

**Issue by lishine** [tannerlinsley/react-virtual#6]
Do you plan something like react-window for this lib?
If not, then is it only for small lists or why is it good enough?

**Comment by tannerlinsley** [comment]
I'm not sure what you mean. This library implements most of what React Window does, but using only a hook instead of components. It's also much smaller and has an easier API.

It's for any size list really. I've rendered **millions** of elements already with react-virtual. 

There is now a section in the README that outlines some of the main differences between this library and react-window.

**Comment by lishine** [comment]
Sorry, my bad! I checked the codesandbox but impatiently, elements indeed are deleted.
I looked at the code briefly. It is so small relatively to react-window! How did you manage to do it ?!

**Comment by lishine** [comment]
BTW I implemented columns masonry with react-window by stacking all the columns inside one row and using margins/translate to move them up/down.
https://github.com/lishine/unsplash-search/tree/dev
I can try to use your lib.
Also I want to try another way to implement - put each column inside different list and scroll them together.
