### ISSUE TITLE
jank on dynamic infinite lists

### ISSUE THREAD

**Issue by Aidenkwok** [tannerlinsley/react-virtual#83]
I've taken the infinte scrolling example and made it dynamic height based on the index. The list jumps down whenever new rows have been fetched.

https://codesandbox.io/s/eager-williamson-2ydyo?file=/src/index.js

**Comment by mattmikolay** [comment]
Were you able to find a solution? I'm experiencing this issue using React Virtual v2.4.0 on an infinite scrolling list using dynamic measurement rendering.

**Comment by mattmikolay** [comment]
From what I can tell, this issue occurs when a new page of data is loaded, triggering a change in the `size` argument passed to the `useVirtual` hook. When this happens, the `useIsomorphicLayoutEffect` hook is triggered, clearing the measure cache:

https://github.com/tannerlinsley/react-virtual/blob/7ad46288d5362ce94d600357f8cba087e6adbe63/src/index.js#L134-L139

The sizes of elements that were already measured dynamically and previously rendered to the screen are cleared from the cache, which causes `calculateRange` to return different `start` and `end` values than the range that was shown on screen prior to the page load.

**Comment by nctay** [comment]
@mattmikolay thanks! I've spent days trying to find out what is happening with scroll. 
@tannerlinsley what's the point of this effect? I've deleted this hook from source code and  infinite list with dynamic size row now works fine.

**Comment by mattmikolay** [comment]
@nctay No problem!

> what's the point of this effect?

Tanner could confirm, but I'm willing to bet it's to handle the case where an entirely new list is being rendered. On the first render, React Virtual might render an array of items `[A, B, C]`. On the next render, the array could change to `[C, D, E, F]`. While the array's size only increased by one, its elements changed entirely, so we should not preserve the existing measurements.

I've had success using a [custom fork of React Virtual](https://github.com/mattmikolay/react-virtual/tree/cache-by-key) that removes the aforementioned `useIsomorphicLayoutEffect` and introduces measurement caching by ID rather than an item's position in the list. I added a `keyExtractor` option of type `(index: number) => number | string` to `useVirtual` that is meant to return a unique ID for any item in the list, given its index.

I'd be happy to open a PR if Tanner feels this approach is the right solution. I haven't tested my changes since the addition of the `measure` function in #55, though.

**Comment by nctay** [comment]
@mattmikolay wow, your fork works like a charm! Thank's a lot! Hope Tanner will use your solution.

**Comment by tannerlinsley** [comment]
If you can integrate the latest changes I would love to see a PR for unique key tracking

**Comment by mattmikolay** [comment]
@tannerlinsley Great! I'll have a PR for you shortly. Thanks.

**Comment by mattmikolay** [comment]
@tannerlinsley #107 is ready for review, at your convenience. 🙏
